MERGE INTO SCC_CODE (CODE, USED) KEY(CODE) VALUES ('SCC-1001', FALSE);
MERGE INTO SCC_CODE (CODE, USED) KEY(CODE) VALUES ('SCC-1002', FALSE);
MERGE INTO SCC_CODE (CODE, USED) KEY(CODE) VALUES ('SCC-2001', FALSE);
